Feature: Reports testing
  Background:
    * configure driver = { type: 'chrome', addOptions: ["--remote-allow-origins=*"] }

  Scenario: testing reports 1
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(5000)
    Then waitForUrl('http://localhost:3000/home')
    And delay(1000)
    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And delay(1000)
    And select("//*[@id='Dropdown-option-report']",'1').click()
    And delay(1000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    Then waitForUrl('http://localhost:3000/reports')
    And delay(1000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[4]/input")
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[7]/input")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/center/button")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/thead/tr/th[6]")
    And delay(3000)
    Then click("//*[@id='report-view-btn']")
    And click("/html/body/div[3]/div/div/div[3]/button[1]")
    And delay(5000)


  Scenario: testing reports 2
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(2000)
    And input("//*[@id='esaidDataList']",'1000383243')
    And delay(2000)
    And input("//*[@id='empidDataList']",'102553')
    And click("//*[@id='mySearchButton']")
    And delay(1000)
    When click("//*[@class='btn btn-primary']")
    And scroll("//*[@id='root']/div[3]/div[4]/form/div[1]/div[11]")
    And input("//*[@id='root']/div[3]/div[4]/form/div[2]/div[8]/input",'04-08-2023')
    And delay(3000)
    And select("//*[@id='root']/div[3]/div[4]/form/div[2]/div[9]/select",'Associate released from project').click()
    And delay(3000)
    And input("//*[@id='root']/div[3]/div[4]/form/div[2]/div[10]/input",'10-08-2023')
    And delay(3000)
    And click("//*[@class='btn btn-success']")
    And delay(2000)
    And scroll("//*[@id='root']/div[3]/div[4]/form/div[1]/div[17]")
    And delay(2000)

    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And select("//*[@id='Dropdown-option-report']",'2').click()
    And delay(3000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[3]/input")
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[4]/input")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/center/button")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/thead/tr/th[7]")
    And delay(3000)
    Then click("//*[@id='report-view-btn']")
    And click("/html/body/div[3]/div/div/div[3]/button[1]")
    And delay(5000)

  Scenario: testing reports 3
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(2000)
    And input("//*[@id='esaidDataList']",'1000383243')
    And delay(2000)
    And input("//*[@id='empidDataList']",'102553')
    And click("//*[@id='mySearchButton']")
    And delay(5000)
    When click("//*[@class='btn btn-primary']")
    And scroll("//*[@id='root']/div[3]/div[4]/form/div[1]/div[14]")
    And input("//*[@id='root']/div[3]/div[4]/form/div[2]/div[11]/input",'15-08-2023')
    And delay(2000)
    And driver.inputFile("//*[@id='fileupload']",'Testimage.png')
    And delay(2000)
    And click("//*[@class='btn btn-success']")
    And delay(2000)
    And scroll("//*[@id='root']/div[3]/div[4]/form/div[1]/div[17]")
    And delay(2000)

    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And select("//*[@id='Dropdown-option-report']",'3').click()
    And delay(3000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[4]/input")
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[9]/input")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/center/button")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/thead/tr/th[8]")
    And delay(3000)
    Then click("//*[@id='report-view-btn']")
    And click("/html/body/div[3]/div/div/div[3]/button[2]")
    And delay(5000)


  Scenario: testing reports 4
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(2000)
    And input("//*[@id='esaidDataList']",'1000383243')
    And delay(2000)
    And input("//*[@id='empidDataList']",'102553')
    And click("//*[@id='mySearchButton']")
    And delay(5000)
    When click("//*[@class='btn btn-primary']")
    And scroll("//*[@id='root']/div[3]/div[4]/form/div[1]/div[17]")
    And input("//*[@id='root']/div[3]/div[4]/form/div[2]/div[13]/input",'1235974')
    And delay(2000)
    And input("//*[@id='root']/div[3]/div[4]/form/div[2]/div[14]/input",'20-08-2023')
    And delay(2000)
    And driver.inputFile("//*[@id='fileupload2']",'Testimage.png')
    And delay(2000)
    And click("//*[@class='btn btn-success']")
    And delay(2000)
    And scroll("//*[@id='root']/div[3]/div[4]/form/div[1]/div[17]")
    And delay(2000)

    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And select("//*[@id='Dropdown-option-report']",'3').click()
    And delay(3000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[5]/input")
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[7]/input")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/center/button")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/thead/tr/th[9]")
    And delay(3000)
    Then click("//*[@id='report-view-btn']")
    And click("/html/body/div[3]/div/div/div[3]/button[1]")
    And delay(5000)


  Scenario: testing reports 5
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(2000)
    Then waitForUrl('http://localhost:3000/home')
    And delay(1000)
    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And delay(1000)
    And select("//*[@id='Dropdown-option-report']",'5').click()
    And delay(3000)
    Then select("//*[@id='root']/div[1]/div[2]/div[1]/select[2]",'CIDTRUE').click()
    And delay(3000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[5]/input")
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[7]/input")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/center/button")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/thead/tr/th[10]")
    And delay(3000)
    Then click("//*[@id='report-view-btn']")
    And click("/html/body/div[3]/div/div/div[3]/button[1]")
    And delay(5000)


  Scenario: testing reports 6
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(2000)
    Then waitForUrl('http://localhost:3000/home')
    And delay(1000)
    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And delay(1000)
    And select("//*[@id='Dropdown-option-report']",'6').click()
    And delay(3000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[8]/input")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[1]/div/div/div[11]/label")
    And delay(3000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[11]/input")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/center/button")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/thead/tr/th[7]")
    And delay(3000)
    Then click("//*[@id='report-view-btn']")
    And click("/html/body/div[3]/div/div/div[3]/button[2]")
    And delay(5000)

  Scenario: testing reports 7
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(2000)
    Then waitForUrl('http://localhost:3000/home')
    And delay(1000)
    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And delay(1000)
    And select("//*[@id='Dropdown-option-report']",'7').click()
    And delay(2000)
    And select("/html/body/div/div[1]/div[2]/div[1]/div/div/select",'8').click()
    And click("//*[@id='report-view-btn2']")
    And delay(2000)

  Scenario: testing reports 8 & 9
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(2000)
    Then waitForUrl('http://localhost:3000/home')
    And delay(1000)
    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And delay(1000)
    And select("//*[@id='Dropdown-option-report']",'8').click()
    And delay(3000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    Then scroll("//*[@id='root']/div[2]/div[1]/div/div/div[17]/label")
    And delay(3000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[17]/input")
    And delay(1000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[18]/input")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/center/button")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/thead/tr/th[10]")
    And delay(3000)
    Then click("//*[@id='report-view-btn']")
    And click("/html/body/div[3]/div/div/div[3]/button[2]")
    And delay(5000)

    And select("//*[@id='Dropdown-option-report']",'9').click()
    And delay(3000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    Then scroll("//*[@id='root']/div[2]/div[1]/div/div/div[10]/label")
    And delay(3000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[10]/input")
    And delay(1000)
    Then click("//*[@id='root']/div[2]/div[1]/div/div/div[12]/input")
    And delay(2000)
    Then click("//*[@id='root']/div[2]/div[1]/div/center/button")
    And delay(1000)
    Then scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/thead/tr/th[8]")
    And delay(3000)
    Then click("//*[@id='report-view-btn']")
    And click("/html/body/div[3]/div/div/div[3]/button[1]")
    And delay(5000)

  Scenario: testing reports 10
    Given driver 'http://localhost:3000/'
    And driver.maximize()
    And delay(2000)
    Then waitForUrl('http://localhost:3000/')
    And delay(1000)
    And input("//*[@id='Login-username']/input",'dev_user@cognizant.com')
    And input("//*[@id='Login-password']/input",'12345678')
    Then select("//*[@id='Login-role']/select",'PMO').click()
    When click("//*[@id='Login-button']")
    And delay(2000)
    Then waitForUrl('http://localhost:3000/home')
    And delay(1000)
    Then click("//*[@id='reports']")
    Then waitForUrl('http://localhost:3000/reports')
    And delay(1000)
    And select("//*[@id='Dropdown-option-report']",'10').click()
    And delay(2000)
    And click("//*[@id='report-view-btn2']")
    And delay(2000)
    And scroll("//*[@id='root']/div[2]/div[2]/div[2]/div/table/tbody/tr[14]/td[1]")
    And click("//*[@id='report-view-btn']")
    And delay(1000)
    When click("/html/body/div[3]/div/div/div[3]/button[2]")
    And delay(2000)

